# Generated by Django 4.2.15 on 2024-08-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0027_alter_instagramcomment_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dummytable",
            name="company",
        ),
    ]
